# Site
name: 'Naveen Jujaray'
description: 'Blog'
logo: 'assets/images/iconk.png' 
favicon: 'assets/images/iconk.png'
baseurl: ''
url: 'https://naveenjujaray.js.org'
disqus: njblog
email: 'jujaraynaveen@gmail.com'
mailchimp-list: ''
twitter: naveenjujaray

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    Sal:
      name:           Naveen Jujaray
      bio:            "Hi, I am Naveen Jujaray, Owner of this blog..."
      email:          jujaraynaveen@gmail.com
      twitter:        https://twitter.com/naveenjujaray

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: Naveen Jujaray
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]